language: python
python:
- '3.6'
script:
- tox -c tox.ini -e $TENV
install:
- pip install setuptools wheel tox codecov pipenv
- pip install --force-reinstall -U "pip<19"
matrix:
  include:
  - python: "3.6"
    env: TENV=py36
  - python: "pypy3"
    env: TENV=pypy3
deploy:
  provider: pypi
  user: "oddjobz"
  skip_existing: true
  on:
    branch: master
  password:
    secure: LfuJ+1W9v1jIajSyh3MEOwbeXqs7q4UWUoTCcGO3FiAKhSt2TNpSTsTwB0sI25fAiRc970C/R7ftqi7ihwbhIaKmkWTIIwjJ7vyGZ3X6mhgDWafO0EwvK7CT/t6v68qQCIwZUfvgBHrgq9Cmc1jF7BYa5kxG9hcZKznHXJgUUkeUS1JNT58xalVg6yeyq9xBPq6LpwhJVWCFmUKLlpxPy4cWqhU1aY2Y/65xBN8LZ9Oj80ieyCLZA/54mmJSRCQSBwvkZJK2AnuSReVLVcHXfT02/LCNCnmsFOIuMt0a9hHuXdwEb68iBacgRh8R7S5diWi3gVJQOqk7d+IE8mhqM7otnwAKn2rs/GDKAVXc7NAerG5uhm7cxzPbFOkX4ag2sjY7po3NlzXg76QbRsNZjnJYBGyzUPOG7d/kJMuEf/osQOZIra30lUMJRMT5woAsaqgukJH399GFLVD0ithp0GhtZwG5FdUIcTTlysJAeP/iDl8zw8brW1ug5nYJEuu5p8GEyqqjs3d26KnwA1gP4fVAxIK9MLRTLGt67QskS45y9pnIzDu53JOpw86D43S7rwv5msQN4kPk3I0b4io/n2YGEaDDNPdP